# Generated by Django 4.0.6 on 2022-07-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя персонажа')),
                ('second_name', models.CharField(max_length=255, verbose_name='Фамилия персонажа')),
                ('last_name', models.CharField(max_length=255, verbose_name='Отчество персонажа')),
                ('slug', models.SlugField(default='x', unique=True)),
                ('age', models.PositiveSmallIntegerField(default=1, verbose_name='Возраст')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фотография')),
                ('info', models.TextField(blank=True, verbose_name='Краткая биография')),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название голосования')),
                ('slug', models.SlugField(default='x', unique=True)),
                ('start_date', models.DateTimeField(verbose_name='Дата начала голосования')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания голосования')),
                ('max_votes', models.PositiveIntegerField(default=1, verbose_name='Максимальное количество голосов')),
                ('characters', models.ManyToManyField(to='voting.character', verbose_name='Персонажи голосования')),
            ],
        ),
    ]
